salla_analytics:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 4
      database: 'salla_analytics'
      schema: 'main'
      schema_directory: '../data_warehouse'
      schemas_and_paths:
        main: '../data_warehouse/raw_salla_data.db'
        main_staging: '../data_warehouse/main_staging.db'
        main_intermediate: '../data_warehouse/main_intermediate.db'
        main_marts: '../data_warehouse/main_marts.db'
