version: 2

sources:
  - name: raw
    description: >
      Bronze layer containing raw data loaded from source CSV files that mock a backend database.
      This represents the extract and load phases of ELT. No transformations are applied at this layer.
      Important columns are defined and tested below.

    schema: main

    tables:
      - name: customers
        description: Raw customer data including location information
        columns:
          - name: customer_id
            description: Order reference key
            tests:
              - not_null
          - name: customer_unique_id
            description: Unique identifier for each customer
            tests:
              - not_null
          - name: customer_city
            description: City where customer resides
          - name: customer_state
            description: State where customer resides

      - name: orders
        description: Raw orders data with lifecycle timestamps
        columns:
          - name: order_id
            description: Unique order identifier
            tests:
              - not_null
              - unique
          - name: customer_id
            description: Reference to customer
            tests:
              - not_null
          - name: order_status
            description: Current order status (delivered, shipped, cancelled, etc.)
          - name: order_purchase_timestamp
            description: When the order was placed
          - name: order_delivered_customer_date
            description: When order was delivered to customer
          - name: order_estimated_delivery_date
            description: Estimated delivery date shown to customer

      - name: order_items
        description: Raw order line items with pricing details
        columns:
          - name: order_id
            description: Order reference key
            tests:
              - not_null
          - name: order_item_id
            description: Sequential item number within order
            tests:
              - not_null
          - name: product_id
            description: Product reference key
            tests:
              - not_null
          - name: seller_id
            description: Seller/store reference key
            tests:
              - not_null
          - name: price
            description: Item price
            tests:
              - not_null
          - name: freight_value
            description: Shipping price
            tests:
              - not_null

      - name: products
        description: Raw product catalog data
        columns:
          - name: product_id
            description: Unique product identifier
            tests:
              - not_null
              - unique
          - name: product_category_name
            description: Product category (in Portuguese)
